Init branch
GTBitsOfGood/angels-among-us pull request #108
Opened 2023-09-06 17:29 UTC by aeluro1

Implement 'use my preferences' button

Issue Number(s): #88

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria are met
- [ ] Database schema docs have been updated or are not necessary
- [ ] Code follows design and style guidelines
- [ ] Commits follow guidelines (concise, squashed, etc)
- [x] Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### Critical Changes

- Database change/migration to run
- Environment config change
- Breaking API change

### Testing

WIP

2023-09-15 00:26 UTC, katsukixyz reviewed
Nice job on this! Just a couple minor comments. Great work on the testing.

2023-09-15 00:26 UTC, katsukixyz commented on web/__tests__/components/Feed.unit.test.tsx
> +// Function to count the number of filter options
Use JSDoc here to show the comment in the IDE, for all comments that describe a function

2023-09-15 00:26 UTC, katsukixyz commented on web/__tests__/components/Feed.unit.test.tsx
> +describe("[Misc] User Preferences - Unit Test", () => {
Use `[Feed] Import User Preferences - Unit Test`

2023-09-15 00:26 UTC, katsukixyz commented on web/__tests__/components/Feed.unit.test.tsx
> + */
Add `@group` tags like in `api/account/account.unit.test.ts` - it allows us to run groups of tests. The groups should be:

```
components/feed
components
unit
```

2023-09-15 00:26 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +  [key: string]: Option[];
Is there a way you can make this type more specific? The keys are limited to the filter keys

2023-09-15 00:26 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +        description: "Dogs not known to be good with:",
This filter is for users to see dogs that are confirmed to be good with men, women, etc. I believe we updated the wording but didn't change the key last semester. Consider changing the key instead.

2023-09-15 00:26 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +function getPrefFilters(userData: IUser | null): SelectedFilters | null {
Consider writing a JSDoc comment here to explain the function and what it returns

2023-09-15 00:26 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +  };
Define these outside of this function

2023-09-15 00:26 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +  const parseOptArr = (opts: Option[], prefArr: any[] | undefined):  Option[] => (
Is it possible to strongly type `prefArr`?

2023-09-15 00:26 UTC, katsukixyz commented on web/__tests__/components/Feed.unit.test.tsx
> +  });
Can you write another test for 1 of them being checked and the other unchecked?

2023-09-15 19:39 UTC, katsukixyz reviewed
Excellent stuff, just 1 minor comment that probably needs to be re-looked at by the LT.

2023-09-15 19:39 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +        allSelected: false,
Keep this as `true` - even though the filter is "Breed Restrictions" I think it acts as an _inclusive_ filter rather than an _exclusive_ one.

2023-09-15 19:42 UTC, katsukixyz commented
Could you merge in #110 before I send it off to the rest of the LT? It resolves the `userData` update issue after updating it via the profile.

2023-09-15 19:46 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +        allSelected: false,
Disregard this - just read the note written by PM. Approving!

2023-09-15 19:46 UTC, katsukixyz approved these changes

2023-09-15 20:33 UTC, katsukixyz requested changes
Oh one more thing. I think there's an issue with the mapping for house trained and spayed/neutered status. When the user's value is `"yes"` for house trained, this means that the user is able to foster dogs that are **not** house trained. Similarly, for spay/neuter status, this means that the user is able to foster dogs that are **not** spayed/neutered. 

When `"no"` for house trained, the user is **not** able to foster dogs that are **not** house trained. When `"no"` for spay/neuter status, the user is **not** able to foster dogs that are **not** spayed/neutered.

Therefore, a user's `"no"` for house trained should mark the corresponding checkbox since the dogs shown must be house trained. A user's `"no"` for spay/neuter status should also mark the checkbox since the dogs shown must be spayed/neutered. 

A `"yes"` for both should keep the checkboxes unchecked since the dog can be either house trained or not house trained and the user would still be okay. Same thing for spay/neuter status. Sorry for not catching that earlier.

2023-09-16 00:47 UTC, katsukixyz approved these changes
Approving this with a nit! I'll send this over to the rest of the LT now. Hold off on merging it in until their comments are in! Great work on this John.

2023-09-16 00:47 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +  inverse: boolean = false
Nit: add a `@param` for `inverse`.

2023-09-16 05:32 UTC, katsukixyz commented on web/components/Feed/Feed.tsx
> +        allSelected: false,
Gah, after some discussion it seems that we're going with `allSelected: true`. I'm so sorry about the back and forth.

2023-09-19 13:48 UTC, rohan-chadha commented
Nothing from me, this looks great!

2023-09-19 21:48 UTC, closed without merging